import type { Plan, PlanPeriod } from "@/types";

export const PLAN_PERIOD_LABELS: Record<PlanPeriod, string> = {
  MONTHLY: "Mensal",
  SEMIANNUAL: "Semestral",
  ANNUAL: "Anual",
  FULL: "Full",
};

export const PLANS: Plan[] = [
  {
    id: "plan_1",
    name: "Mensal 1x",
    period: "MONTHLY",
    frequency: "1x",
    priceMonthly: 129,
    totalPrice: 129,
    description: "Entrada consistente para quem quer comecar com tecnica e ritmo.",
    benefits: ["1 treino por semana", "Acesso ao app do aluno", "Acompanhamento basico"],
  },
  {
    id: "plan_2",
    name: "Mensal 2x",
    period: "MONTHLY",
    frequency: "2x",
    priceMonthly: 159,
    totalPrice: 159,
    description: "Boa frequencia para evoluir tecnica, condicionamento e constancia.",
    benefits: ["2 treinos por semana", "Controle de presenca", "Suporte da recepcao"],
  },
  {
    id: "plan_3",
    name: "Mensal 3x",
    period: "MONTHLY",
    frequency: "3x",
    priceMonthly: 179,
    totalPrice: 179,
    featured: true,
    badge: "MAIS ESCOLHIDO",
    description: "O plano ideal para acelerar sua evolucao sem perder rotina.",
    benefits: ["3 treinos por semana", "Melhor custo-beneficio mensal", "Ritmo forte de progresso"],
  },
  {
    id: "plan_4",
    name: "Semestral 1x",
    period: "SEMIANNUAL",
    frequency: "1x",
    priceMonthly: 119,
    totalPrice: 714,
    description: "Compromisso de medio prazo para encaixar treino na agenda.",
    benefits: ["6 meses de permanencia", "Valor mensal reduzido", "Planejamento de rotina"],
  },
  {
    id: "plan_5",
    name: "Semestral 2x",
    period: "SEMIANNUAL",
    frequency: "2x",
    priceMonthly: 143,
    totalPrice: 858,
    description: "Estrutura equilibrada para ganhar base, cardio e tecnica.",
    benefits: ["2 treinos por semana", "Desconto sobre o mensal", "Mais previsibilidade"],
  },
  {
    id: "plan_6",
    name: "Semestral 3x",
    period: "SEMIANNUAL",
    frequency: "3x",
    priceMonthly: 163,
    totalPrice: 978,
    featured: true,
    badge: "ALTA EVOLUCAO",
    description: "Para quem quer treinar serio, manter frequencia e colher resultado.",
    benefits: ["3 treinos por semana", "Melhor ritmo semestral", "Compromisso forte com evolucao"],
  },
  {
    id: "plan_7",
    name: "Anual 1x",
    period: "ANNUAL",
    frequency: "1x",
    priceMonthly: 109,
    totalPrice: 1308,
    description: "Entrada anual com o menor custo para manter consistencia.",
    benefits: ["12 meses de academia", "Economia no valor mensal", "Base de longo prazo"],
  },
  {
    id: "plan_8",
    name: "Anual 2x",
    period: "ANNUAL",
    frequency: "2x",
    priceMonthly: 119,
    totalPrice: 1428,
    description: "Plano anual para quem ja sabe que quer levar o treino a serio.",
    benefits: ["2 treinos por semana", "Custo mensal competitivo", "Rotina mais previsivel"],
  },
  {
    id: "plan_9",
    name: "Anual 3x",
    period: "ANNUAL",
    frequency: "3x",
    priceMonthly: 149,
    totalPrice: 1788,
    featured: true,
    badge: "PREMIUM",
    description: "Melhor combinacao entre frequencia, resultado e valor no longo prazo.",
    benefits: ["3 treinos por semana", "Maior economia anual", "Plano premium da rotina"],
  },
  {
    id: "plan_10",
    name: "Full - Ilimitado",
    period: "FULL",
    frequency: "UNLIMITED",
    priceMonthly: 250,
    totalPrice: 250,
    description: "Acesso amplo para quem vive a academia de forma intensa.",
    benefits: ["Treinos ilimitados", "Maior liberdade de agenda", "Experiencia completa"],
  },
  {
    id: "plan_11",
    name: "Full - Desconto Social",
    period: "FULL",
    frequency: "UNLIMITED",
    priceMonthly: 185,
    totalPrice: 185,
    badge: "CONDICAO ESPECIAL",
    description: "Opcao social com acesso full mediante disponibilidade e avaliacao interna.",
    benefits: ["Treinos ilimitados", "Condicao diferenciada", "Acesso ao ecossistema da academia"],
  },
];

export const PLAN_PRICES: Record<string, number> = Object.fromEntries(
  PLANS.map((plan) => [plan.id, plan.totalPrice]),
);

export function groupPlansByPeriod() {
  return {
    monthly: PLANS.filter((plan) => plan.period === "MONTHLY"),
    semiannual: PLANS.filter((plan) => plan.period === "SEMIANNUAL"),
    annual: PLANS.filter((plan) => plan.period === "ANNUAL"),
    full: PLANS.filter((plan) => plan.period === "FULL"),
  };
}
